# --- Perfil de desenvolvimento ---
# Ative com: -Dspring.profiles.active=dev

# H2 Console habilitado apenas em dev
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# SQL visível no console em dev
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
